// ==========================================
// 8. RECURRING TASK MANAGER
// ==========================================

// Get all templates for the UI
function getRecurringTemplates() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sh = ss.getSheetByName('Recurring_Templates');
  if (!sh || sh.getLastRow() < 2) return [];
  
  const data = sh.getRange(2, 1, sh.getLastRow()-1, 7).getValues();
  return data.map(r => ({
    id: r[0], title: r[1], type: r[2], freq: r[3], 
    subtasks: r[4], nextDate: r[5] ? new Date(r[5]).toISOString().split('T')[0] : '', owner: r[6]
  }));
}

// Save or Update a Template
function saveRecurringTemplate(form) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let sh = ss.getSheetByName('Recurring_Templates');
  if (!sh) {
    sh = ss.insertSheet('Recurring_Templates');
    sh.appendRow(['ID', 'Title', 'Type', 'Frequency', 'SubTasks_JSON', 'Next_Date', 'Owner']);
  }
  
  const id = form.id || 'REC-' + Date.now();
  const subtasksJSON = JSON.stringify(form.subtasks || []); // Store subtasks as JSON string
  const rowData = [id, form.title, form.type, form.freq, subtasksJSON, form.nextDate, form.owner];
  
  const data = sh.getDataRange().getValues();
  let found = false;
  
  for (let i = 1; i < data.length; i++) {
    if (String(data[i][0]) === String(id)) {
      sh.getRange(i + 1, 1, 1, 7).setValues([rowData]);
      found = true;
      break;
    }
  }
  
  if (!found) sh.appendRow(rowData);
  return { success: true };
}

// Delete a Template
function deleteRecurringTemplate(id) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sh = ss.getSheetByName('Recurring_Templates');
  const data = sh.getDataRange().getValues();
  for (let i = 1; i < data.length; i++) {
    if (String(data[i][0]) === String(id)) {
      sh.deleteRow(i + 1);
      break;
    }
  }
  return { success: true };
}

// THE GENERATOR: Run this on a Daily Trigger
// THE GENERATOR: Run this on a Daily Trigger
function generateRecurringTasks() {
  // PERF-05: Note - This function currently uses saveItem() inside a loop, which does individual
  // sheet read/writes. In the future, this should be refactored to gather all new tasks/subtasks
  // and append/batch write them to their respective sheets in a single operation.
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sh = ss.getSheetByName('Recurring_Templates');
  if (!sh || sh.getLastRow() < 2) return;
  
  const data = sh.getRange(2, 1, sh.getLastRow()-1, 7).getValues();
  const today = new Date();
  today.setHours(0,0,0,0);
  
  data.forEach((r, i) => {
    const nextDate = new Date(r[5]);
    nextDate.setHours(0,0,0,0);
    
    // If Next Date is Today or Past
    if (nextDate <= today) {
      
      // 1. Create Main Task/Project using saveItem
      // We leave ID blank so the system generates a standard ID (e.g. ITEM-1050)
      const parentResult = saveItem({
        ID: '', 
        Title: r[1], 
        Type: r[2], 
        Owner: r[6], 
        Status: 'To Do', 
        DueDate: r[5], 
        Desc: 'Auto-generated recurring task.'
      });
      
      // Capture the ID correctly generated by the system
      const parentId = parentResult.id; 
      
      // 2. Create Sub-Tasks
      if (r[4] && parentId) {
        try {
          const subs = JSON.parse(r[4]);
          subs.forEach((sub) => {
             // Calculate Offset Date
             let subDate = new Date(r[5]); // Start with Parent Due Date
             const offset = parseInt(sub.offset) || 0;
             subDate.setDate(subDate.getDate() + offset); // Add offset days
             
             const subDateStr = subDate.toISOString().split('T')[0];

             // Create Sub-task linked to the new Parent ID
             saveItem({
               ID: '', 
               Title: sub.title, 
               Type: 'Sub-task', 
               ParentID: parentId, 
               Owner: r[6], 
               Status: 'To Do', 
               DueDate: subDateStr
             });
          });
        } catch(e) { console.error('JSON Error', e); }
      }
      
      // 3. Calculate New Next Date
      let newDate = new Date(nextDate);
      if (r[3] === 'Daily') newDate.setDate(newDate.getDate() + 1);
      if (r[3] === 'Weekly') newDate.setDate(newDate.getDate() + 7);
      if (r[3] === 'Monthly') newDate.setMonth(newDate.getMonth() + 1);
      if (r[3] === 'Yearly') newDate.setFullYear(newDate.getFullYear() + 1);
      
      // Update Template with new date
      sh.getRange(i + 2, 6).setValue(newDate);
    }
  });
}
// ==========================================
// 9. TYPE WORKFLOW MANAGER (SOPs)
// ==========================================

// Get all Type Templates for UI
function getTypeTemplates() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sh = ss.getSheetByName('Type_Templates');
  if (!sh || sh.getLastRow() < 2) return [];
  
  // Columns: [Type, SubTasks_JSON]
  const data = sh.getRange(2, 1, sh.getLastRow()-1, 2).getValues();
  return data.map(r => ({ type: r[0], subtasks: r[1] }));
}

// Save a Type Template
function saveTypeTemplate(type, subtasks) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let sh = ss.getSheetByName('Type_Templates');
  if (!sh) {
    sh = ss.insertSheet('Type_Templates');
    sh.appendRow(['Type', 'SubTasks_JSON']);
  }
  
  const json = JSON.stringify(subtasks || []);
  const data = sh.getDataRange().getValues();
  let found = false;
  
  // Update existing row if Type exists
  for (let i = 1; i < data.length; i++) {
    if (String(data[i][0]) === String(type)) {
      sh.getRange(i + 1, 2).setValue(json);
      found = true;
      break;
    }
  }
  
  // Or append new row
  if (!found) sh.appendRow([type, json]);
  return { success: true };
}

// HELPER: Auto-generate subtasks based on Type
function applyTypeTemplate(parentId, type, owner, dueDateStr) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sh = ss.getSheetByName('Type_Templates');
  if (!sh || sh.getLastRow() < 2) return;
  
  const data = sh.getRange(2, 1, sh.getLastRow()-1, 2).getValues();
  const template = data.find(r => r[0] === type);
  
  if (template && template[1]) {
    try {
      const subs = JSON.parse(template[1]);
      const parentDate = dueDateStr ? new Date(dueDateStr) : new Date();

      subs.forEach((sub) => {
         // Calculate Offset Date
         let subDate = new Date(parentDate);
         const offset = parseInt(sub.offset) || 0;
         subDate.setDate(subDate.getDate() + offset);
         const subDateStr = subDate.toISOString().split('T')[0];

         // Use saveItem instead of addProject
         saveItem({
           ID: '', 
           Title: sub.title, 
           Type: 'Sub-task', 
           ParentID: parentId, 
           Owner: owner, 
           Status: 'To Do', 
           DueDate: subDateStr
         });
      });
      console.log(`Applied ${type} template to ${parentId}`);
    } catch(e) { console.error('Template Error', e); }
  }
}

function getPerformanceReport(startStr, endStr, ownerFilter) {
  const ss = SpreadsheetApp.getActive();
  const tz = ss.getSpreadsheetTimeZone(); 
  
  const sheets = ['Projects', 'Tasks', 'Projects_Archive', 'Tasks_Archive'];
  let results = [];

  sheets.forEach(name => {
    const sh = ss.getSheetByName(name);
    if (!sh || sh.getLastRow() < 2) return;
    
    const data = sh.getDataRange().getValues();
    const headers = data[0] || [];
    const isProject = name.includes('Project');
    
    const statusIdx = headers.indexOf('Status') !== -1 ? headers.indexOf('Status') : 6;
    const ownerIdx = headers.indexOf('Owner') !== -1 ? headers.indexOf('Owner') : (isProject ? 3 : 4);
    let doneDateIdx = headers.indexOf('CompletedDate');
    if (doneDateIdx === -1) doneDateIdx = headers.indexOf('Completed_Date');
    if (doneDateIdx === -1) doneDateIdx = isProject ? 32 : 18;
    const dueDateIdx = headers.indexOf('DueDate') !== -1 ? headers.indexOf('DueDate') : 5;
    
    for (let i = 1; i < data.length; i++) {
      const row = data[i];
      const status = row[statusIdx];
      const rowOwner = row[ownerIdx]; 
      
      if (ownerFilter && rowOwner !== ownerFilter) continue;
      if (status !== 'Done') continue;

      let doneDate = row[doneDateIdx];
      // Fallback: If no "Done Date" recorded, use "Due Date"
      if (!doneDate || doneDate === '') doneDate = row[dueDateIdx]; 
      
      let dString = "";
      try {
         const dateObj = (doneDate instanceof Date) ? doneDate : new Date(doneDate);
         dString = Utilities.formatDate(dateObj, tz, "yyyy-MM-dd");
      } catch(e) { continue; }

      if (dString >= startStr && dString <= endStr) {
         let isLate = false;
         if (row[5]) { 
            const dueString = Utilities.formatDate(new Date(row[5]), tz, "yyyy-MM-dd");
            if (dueString < dString) isLate = true;
         }

         results.push({
           id: row[0],
           title: row[1],
           type: row[2],
           owner: rowOwner,
           completed: new Date(doneDate).toLocaleDateString(), 
           isLate: isLate
         });
      }
    }
  });
  
  return results.sort((a,b) => new Date(b.completed) - new Date(a.completed));
}

// ==========================================
// 5. DRAG & DROP HANDLER (Robust Version)
// ==========================================
function updateCardRank(form) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const id = String(form.ID).trim();
  const status = form.Status;
  const rank = form.Rank;
  const doneDate = form.CompletedDate;

  const tryUpdate = (sheetName) => {
    const sh = ss.getSheetByName(sheetName);
    if (!sh || sh.getLastRow() < 2) return false;
    
    const headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
    const idColIdx = headers.indexOf('ID') + 1;
    const statusColIdx = headers.indexOf('Status') + 1;
    const titleColIdx = headers.indexOf('Title') + 1;
    const rankColIdx = headers.indexOf('Rank') + 1;
    let dateColIdx = headers.indexOf('CompletedDate') + 1;
    if (dateColIdx === 0) dateColIdx = headers.indexOf('Completed_Date') + 1;

    if (idColIdx === 0) return false;

    const data = sh.getRange(2, idColIdx, sh.getLastRow() - 1, 1).getValues();
    let row = -1;
    
    for (let i = 0; i < data.length; i++) {
      if (String(data[i][0]).trim() === id) {
        row = i + 2; 
        break;
      }
    }

    if (row > -1) {
      // 1. GET OLD STATUS FIRST
      const oldStatus = statusColIdx > 0 ? sh.getRange(row, statusColIdx).getValue() : '';
      const title = titleColIdx > 0 ? sh.getRange(row, titleColIdx).getValue() : ''; 
      const user = Session.getActiveUser().getEmail();
      
      // 2. LOG IF CHANGED
      if (oldStatus !== status && statusColIdx > 0) {
          logActivity_(user, id, title, "Moved", `Moved to ${status}`);
          // Update Status Cell
          sh.getRange(row, statusColIdx).setValue(status);
      }
      
      // 3. Update Rank (uses dynamic rankColIdx so Requestor is never overwritten)
      if (rankColIdx > 0 && rank !== undefined && rank !== null) {
          sh.getRange(row, rankColIdx).setValue(rank);
      }

      // 4. Update Date Done (uses dynamic dateColIdx)
      if (doneDate && dateColIdx > 0) {
         sh.getRange(row, dateColIdx).setValue(doneDate);
      }
      return true;
    }
    return false;
  };

  // Execution Order
  let primarySheet = 'Tasks';
  if (id.startsWith('PROJ')) { primarySheet = 'Projects'; }
  else if (id.startsWith('SUB')) { primarySheet = 'Sub_Tasks'; }

  if (tryUpdate(primarySheet)) return;
  if (primarySheet !== 'Tasks') { if (tryUpdate('Tasks')) return; }
  if (primarySheet !== 'Projects') { if (tryUpdate('Projects')) return; }
}

